export const resultThemes = {
  F: {
    label: 'Friends',
    emoji: '\u{1F91D}',
    gradient: 'from-blue-400 to-cyan-300',
    bgColor: '#3b82f6',
    particleColor: '#60a5fa',
    lightColor: '#93c5fd',
    description: 'Best friends forever!',
  },
  L: {
    label: 'Love',
    emoji: '\u2764\uFE0F',
    gradient: 'from-red-500 to-pink-400',
    bgColor: '#ef4444',
    particleColor: '#f87171',
    lightColor: '#fca5a5',
    description: 'True love is in the air!',
  },
  A: {
    label: 'Affection',
    emoji: '\u{1F495}',
    gradient: 'from-pink-400 to-rose-300',
    bgColor: '#ec4899',
    particleColor: '#f472b6',
    lightColor: '#f9a8d4',
    description: 'Sweet affection blooms!',
  },
  M: {
    label: 'Marriage',
    emoji: '\u{1F48D}',
    gradient: 'from-yellow-400 to-amber-300',
    bgColor: '#f59e0b',
    particleColor: '#fbbf24',
    lightColor: '#fde68a',
    description: 'Wedding bells are ringing!',
  },
  E: {
    label: 'Enemies',
    emoji: '\u26A1',
    gradient: 'from-purple-600 to-violet-500',
    bgColor: '#7c3aed',
    particleColor: '#a78bfa',
    lightColor: '#c4b5fd',
    description: 'Rivals to the core!',
  },
  S: {
    label: 'Siblings',
    emoji: '\u{1F46B}',
    gradient: 'from-green-400 to-emerald-300',
    bgColor: '#10b981',
    particleColor: '#34d399',
    lightColor: '#6ee7b7',
    description: 'Family bonds forever!',
  },
  default: {
    bgColor: '#6366f1',
    particleColor: '#818cf8',
    lightColor: '#a5b4fc',
  },
}
